using HVTApp.Model.POCOs;
using Prism.Events;

namespace HVTApp.UI.Events
{
	public partial class AfterRemovePaymentActualEvent : PubSubEvent<PaymentActual> { }
	public partial class AfterRemovePaymentPlannedEvent : PubSubEvent<PaymentPlanned> { }
	public partial class AfterRemoveProductDesignationEvent : PubSubEvent<ProductDesignation> { }
	public partial class AfterRemoveProductTypeDesignationEvent : PubSubEvent<ProductTypeDesignation> { }
	public partial class AfterRemoveProjectTypeEvent : PubSubEvent<ProjectType> { }
	public partial class AfterRemoveCommonOptionEvent : PubSubEvent<CommonOption> { }
	public partial class AfterRemoveAddressEvent : PubSubEvent<Address> { }
	public partial class AfterRemoveCountryEvent : PubSubEvent<Country> { }
	public partial class AfterRemoveDistrictEvent : PubSubEvent<District> { }
	public partial class AfterRemoveLocalityEvent : PubSubEvent<Locality> { }
	public partial class AfterRemoveLocalityTypeEvent : PubSubEvent<LocalityType> { }
	public partial class AfterRemoveRegionEvent : PubSubEvent<Region> { }
	public partial class AfterRemoveCalculatePriceTaskEvent : PubSubEvent<CalculatePriceTask> { }
	public partial class AfterRemoveSumEvent : PubSubEvent<Sum> { }
	public partial class AfterRemoveCurrencyExchangeRateEvent : PubSubEvent<CurrencyExchangeRate> { }
	public partial class AfterRemoveDescribeProductBlockTaskEvent : PubSubEvent<DescribeProductBlockTask> { }
	public partial class AfterRemoveNoteEvent : PubSubEvent<Note> { }
	public partial class AfterRemoveOfferUnitEvent : PubSubEvent<OfferUnit> { }
	public partial class AfterRemovePaymentConditionSetEvent : PubSubEvent<PaymentConditionSet> { }
	public partial class AfterRemoveProductTypeEvent : PubSubEvent<ProductType> { }
	public partial class AfterRemoveProductBlockEvent : PubSubEvent<ProductBlock> { }
	public partial class AfterRemoveProductDependentEvent : PubSubEvent<ProductDependent> { }
	public partial class AfterRemoveProductionTaskEvent : PubSubEvent<ProductionTask> { }
	public partial class AfterRemoveSalesBlockEvent : PubSubEvent<SalesBlock> { }
	public partial class AfterRemoveBankDetailsEvent : PubSubEvent<BankDetails> { }
	public partial class AfterRemoveCompanyEvent : PubSubEvent<Company> { }
	public partial class AfterRemoveCompanyFormEvent : PubSubEvent<CompanyForm> { }
	public partial class AfterRemoveDocumentsRegistrationDetailsEvent : PubSubEvent<DocumentsRegistrationDetails> { }
	public partial class AfterRemoveEmployeesPositionEvent : PubSubEvent<EmployeesPosition> { }
	public partial class AfterRemoveFacilityTypeEvent : PubSubEvent<FacilityType> { }
	public partial class AfterRemoveActivityFieldEvent : PubSubEvent<ActivityField> { }
	public partial class AfterRemoveContractEvent : PubSubEvent<Contract> { }
	public partial class AfterRemoveMeasureEvent : PubSubEvent<Measure> { }
	public partial class AfterRemoveParameterEvent : PubSubEvent<Parameter> { }
	public partial class AfterRemoveParameterGroupEvent : PubSubEvent<ParameterGroup> { }
	public partial class AfterRemoveProductRelationEvent : PubSubEvent<ProductRelation> { }
	public partial class AfterRemovePersonEvent : PubSubEvent<Person> { }
	public partial class AfterRemoveParameterRelationEvent : PubSubEvent<ParameterRelation> { }
	public partial class AfterRemoveSalesUnitEvent : PubSubEvent<SalesUnit> { }
	public partial class AfterRemoveServiceEvent : PubSubEvent<Service> { }
	public partial class AfterRemoveTestFriendAddressEvent : PubSubEvent<TestFriendAddress> { }
	public partial class AfterRemoveTestFriendEvent : PubSubEvent<TestFriend> { }
	public partial class AfterRemoveTestFriendEmailEvent : PubSubEvent<TestFriendEmail> { }
	public partial class AfterRemoveTestFriendGroupEvent : PubSubEvent<TestFriendGroup> { }
	public partial class AfterRemoveDocumentEvent : PubSubEvent<Document> { }
	public partial class AfterRemoveTestEntityEvent : PubSubEvent<TestEntity> { }
	public partial class AfterRemoveTestHusbandEvent : PubSubEvent<TestHusband> { }
	public partial class AfterRemoveTestWifeEvent : PubSubEvent<TestWife> { }
	public partial class AfterRemoveTestChildEvent : PubSubEvent<TestChild> { }
	public partial class AfterRemoveSumOnDateEvent : PubSubEvent<SumOnDate> { }
	public partial class AfterRemoveProductEvent : PubSubEvent<Product> { }
	public partial class AfterRemoveOfferEvent : PubSubEvent<Offer> { }
	public partial class AfterRemoveEmployeeEvent : PubSubEvent<Employee> { }
	public partial class AfterRemoveOrderEvent : PubSubEvent<Order> { }
	public partial class AfterRemovePaymentConditionEvent : PubSubEvent<PaymentCondition> { }
	public partial class AfterRemovePaymentDocumentEvent : PubSubEvent<PaymentDocument> { }
	public partial class AfterRemoveFacilityEvent : PubSubEvent<Facility> { }
	public partial class AfterRemoveProjectEvent : PubSubEvent<Project> { }
	public partial class AfterRemoveUserRoleEvent : PubSubEvent<UserRole> { }
	public partial class AfterRemoveSpecificationEvent : PubSubEvent<Specification> { }
	public partial class AfterRemoveTenderEvent : PubSubEvent<Tender> { }
	public partial class AfterRemoveTenderTypeEvent : PubSubEvent<TenderType> { }
	public partial class AfterRemoveUserEvent : PubSubEvent<User> { }
}
