namespace HVTApp.UI.Lookup
{
	public partial class AddressLookup : LookupItem { }
	public partial class CountryLookup : LookupItem { }
	public partial class DistrictLookup : LookupItem { }
	public partial class LocalityLookup : LookupItem { }
	public partial class LocalityTypeLookup : LookupItem { }
	public partial class RegionLookup : LookupItem { }
	public partial class AdditionalSalesUnitsLookup : LookupItem { }
	public partial class BankDetailsLookup : LookupItem { }
	public partial class CompanyLookup : LookupItem { }
	public partial class CompanyFormLookup : LookupItem { }
	public partial class DocumentsRegistrationDetailsLookup : LookupItem { }
	public partial class EmployeesPositionLookup : LookupItem { }
	public partial class FacilityTypeLookup : LookupItem { }
	public partial class ActivityFieldLookup : LookupItem { }
	public partial class ContractLookup : LookupItem { }
	public partial class MeasureLookup : LookupItem { }
	public partial class ParameterLookup : LookupItem { }
	public partial class ParameterGroupLookup : LookupItem { }
	public partial class ProductRelationLookup : LookupItem { }
	public partial class StandartPaymentConditionsLookup : LookupItem { }
	public partial class PersonLookup : LookupItem { }
	public partial class PaymentPlannedLookup : LookupItem { }
	public partial class PaymentActualLookup : LookupItem { }
	public partial class ParameterRelationLookup : LookupItem { }
	public partial class ProjectUnitLookup : LookupItem { }
	public partial class TenderUnitLookup : LookupItem { }
	public partial class ShipmentUnitLookup : LookupItem { }
	public partial class ProductionUnitLookup : LookupItem { }
	public partial class SalesUnitLookup : LookupItem { }
	public partial class TestFriendAddressLookup : LookupItem { }
	public partial class TestFriendLookup : LookupItem { }
	public partial class TestFriendEmailLookup : LookupItem { }
	public partial class TestFriendGroupLookup : LookupItem { }
	public partial class DocumentLookup : LookupItem { }
	public partial class TestEntityLookup : LookupItem { }
	public partial class TestHusbandLookup : LookupItem { }
	public partial class TestWifeLookup : LookupItem { }
	public partial class TestChildLookup : LookupItem { }
	public partial class CostOnDateLookup : LookupItem { }
	public partial class CostLookup : LookupItem { }
	public partial class CurrencyLookup : LookupItem { }
	public partial class ExchangeCurrencyRateLookup : LookupItem { }
	public partial class ProductLookup : LookupItem { }
	public partial class OfferLookup : LookupItem { }
	public partial class EmployeeLookup : LookupItem { }
	public partial class OrderLookup : LookupItem { }
	public partial class PaymentConditionLookup : LookupItem { }
	public partial class PaymentDocumentLookup : LookupItem { }
	public partial class FacilityLookup : LookupItem { }
	public partial class ProjectLookup : LookupItem { }
	public partial class UserRoleLookup : LookupItem { }
	public partial class SpecificationLookup : LookupItem { }
	public partial class TenderLookup : LookupItem { }
	public partial class TenderTypeLookup : LookupItem { }
	public partial class UserLookup : LookupItem { }
	public partial class OfferUnitLookup : LookupItem { }
}
