using HVTApp.Infrastructure;

namespace HVTApp.UI.Wrapper
{
    public partial class WrapperDataService
    {
        public WrapperDataService(IUnitOfWork unitOfWork)
        {
            CommonOptionWrapperRepository = new CommonOptionWrapperRepository(unitOfWork);
            AddressWrapperRepository = new AddressWrapperRepository(unitOfWork);
            CountryWrapperRepository = new CountryWrapperRepository(unitOfWork);
            DistrictWrapperRepository = new DistrictWrapperRepository(unitOfWork);
            LocalityWrapperRepository = new LocalityWrapperRepository(unitOfWork);
            LocalityTypeWrapperRepository = new LocalityTypeWrapperRepository(unitOfWork);
            RegionWrapperRepository = new RegionWrapperRepository(unitOfWork);
            CalculatePriceTaskWrapperRepository = new CalculatePriceTaskWrapperRepository(unitOfWork);
            SumWrapperRepository = new SumWrapperRepository(unitOfWork);
            CurrencyExchangeRateWrapperRepository = new CurrencyExchangeRateWrapperRepository(unitOfWork);
            DescribeProductBlockTaskWrapperRepository = new DescribeProductBlockTaskWrapperRepository(unitOfWork);
            NoteWrapperRepository = new NoteWrapperRepository(unitOfWork);
            OfferUnitWrapperRepository = new OfferUnitWrapperRepository(unitOfWork);
            PaymentConditionSetWrapperRepository = new PaymentConditionSetWrapperRepository(unitOfWork);
            ProductBlockWrapperRepository = new ProductBlockWrapperRepository(unitOfWork);
            ProductDependentWrapperRepository = new ProductDependentWrapperRepository(unitOfWork);
            ProductionTaskWrapperRepository = new ProductionTaskWrapperRepository(unitOfWork);
            SalesBlockWrapperRepository = new SalesBlockWrapperRepository(unitOfWork);
            BankDetailsWrapperRepository = new BankDetailsWrapperRepository(unitOfWork);
            CompanyWrapperRepository = new CompanyWrapperRepository(unitOfWork);
            CompanyFormWrapperRepository = new CompanyFormWrapperRepository(unitOfWork);
            DocumentsRegistrationDetailsWrapperRepository = new DocumentsRegistrationDetailsWrapperRepository(unitOfWork);
            EmployeesPositionWrapperRepository = new EmployeesPositionWrapperRepository(unitOfWork);
            FacilityTypeWrapperRepository = new FacilityTypeWrapperRepository(unitOfWork);
            ActivityFieldWrapperRepository = new ActivityFieldWrapperRepository(unitOfWork);
            ContractWrapperRepository = new ContractWrapperRepository(unitOfWork);
            MeasureWrapperRepository = new MeasureWrapperRepository(unitOfWork);
            ParameterWrapperRepository = new ParameterWrapperRepository(unitOfWork);
            ParameterGroupWrapperRepository = new ParameterGroupWrapperRepository(unitOfWork);
            ProductRelationWrapperRepository = new ProductRelationWrapperRepository(unitOfWork);
            PersonWrapperRepository = new PersonWrapperRepository(unitOfWork);
            PaymentPlannedListWrapperRepository = new PaymentPlannedListWrapperRepository(unitOfWork);
            PaymentPlannedWrapperRepository = new PaymentPlannedWrapperRepository(unitOfWork);
            PaymentActualWrapperRepository = new PaymentActualWrapperRepository(unitOfWork);
            ParameterRelationWrapperRepository = new ParameterRelationWrapperRepository(unitOfWork);
            SalesUnitWrapperRepository = new SalesUnitWrapperRepository(unitOfWork);
            ServiceWrapperRepository = new ServiceWrapperRepository(unitOfWork);
            TestFriendAddressWrapperRepository = new TestFriendAddressWrapperRepository(unitOfWork);
            TestFriendWrapperRepository = new TestFriendWrapperRepository(unitOfWork);
            TestFriendEmailWrapperRepository = new TestFriendEmailWrapperRepository(unitOfWork);
            TestFriendGroupWrapperRepository = new TestFriendGroupWrapperRepository(unitOfWork);
            DocumentWrapperRepository = new DocumentWrapperRepository(unitOfWork);
            TestEntityWrapperRepository = new TestEntityWrapperRepository(unitOfWork);
            TestHusbandWrapperRepository = new TestHusbandWrapperRepository(unitOfWork);
            TestWifeWrapperRepository = new TestWifeWrapperRepository(unitOfWork);
            TestChildWrapperRepository = new TestChildWrapperRepository(unitOfWork);
            SumOnDateWrapperRepository = new SumOnDateWrapperRepository(unitOfWork);
            ProductWrapperRepository = new ProductWrapperRepository(unitOfWork);
            OfferWrapperRepository = new OfferWrapperRepository(unitOfWork);
            EmployeeWrapperRepository = new EmployeeWrapperRepository(unitOfWork);
            OrderWrapperRepository = new OrderWrapperRepository(unitOfWork);
            PaymentConditionWrapperRepository = new PaymentConditionWrapperRepository(unitOfWork);
            PaymentDocumentWrapperRepository = new PaymentDocumentWrapperRepository(unitOfWork);
            FacilityWrapperRepository = new FacilityWrapperRepository(unitOfWork);
            ProjectWrapperRepository = new ProjectWrapperRepository(unitOfWork);
            UserRoleWrapperRepository = new UserRoleWrapperRepository(unitOfWork);
            SpecificationWrapperRepository = new SpecificationWrapperRepository(unitOfWork);
            TenderWrapperRepository = new TenderWrapperRepository(unitOfWork);
            TenderTypeWrapperRepository = new TenderTypeWrapperRepository(unitOfWork);
            UserWrapperRepository = new UserWrapperRepository(unitOfWork);
        }

        private CommonOptionWrapperRepository CommonOptionWrapperRepository;
        private AddressWrapperRepository AddressWrapperRepository;
        private CountryWrapperRepository CountryWrapperRepository;
        private DistrictWrapperRepository DistrictWrapperRepository;
        private LocalityWrapperRepository LocalityWrapperRepository;
        private LocalityTypeWrapperRepository LocalityTypeWrapperRepository;
        private RegionWrapperRepository RegionWrapperRepository;
        private CalculatePriceTaskWrapperRepository CalculatePriceTaskWrapperRepository;
        private SumWrapperRepository SumWrapperRepository;
        private CurrencyExchangeRateWrapperRepository CurrencyExchangeRateWrapperRepository;
        private DescribeProductBlockTaskWrapperRepository DescribeProductBlockTaskWrapperRepository;
        private NoteWrapperRepository NoteWrapperRepository;
        private OfferUnitWrapperRepository OfferUnitWrapperRepository;
        private PaymentConditionSetWrapperRepository PaymentConditionSetWrapperRepository;
        private ProductBlockWrapperRepository ProductBlockWrapperRepository;
        private ProductDependentWrapperRepository ProductDependentWrapperRepository;
        private ProductionTaskWrapperRepository ProductionTaskWrapperRepository;
        private SalesBlockWrapperRepository SalesBlockWrapperRepository;
        private BankDetailsWrapperRepository BankDetailsWrapperRepository;
        private CompanyWrapperRepository CompanyWrapperRepository;
        private CompanyFormWrapperRepository CompanyFormWrapperRepository;
        private DocumentsRegistrationDetailsWrapperRepository DocumentsRegistrationDetailsWrapperRepository;
        private EmployeesPositionWrapperRepository EmployeesPositionWrapperRepository;
        private FacilityTypeWrapperRepository FacilityTypeWrapperRepository;
        private ActivityFieldWrapperRepository ActivityFieldWrapperRepository;
        private ContractWrapperRepository ContractWrapperRepository;
        private MeasureWrapperRepository MeasureWrapperRepository;
        private ParameterWrapperRepository ParameterWrapperRepository;
        private ParameterGroupWrapperRepository ParameterGroupWrapperRepository;
        private ProductRelationWrapperRepository ProductRelationWrapperRepository;
        private PersonWrapperRepository PersonWrapperRepository;
        private PaymentPlannedListWrapperRepository PaymentPlannedListWrapperRepository;
        private PaymentPlannedWrapperRepository PaymentPlannedWrapperRepository;
        private PaymentActualWrapperRepository PaymentActualWrapperRepository;
        private ParameterRelationWrapperRepository ParameterRelationWrapperRepository;
        private SalesUnitWrapperRepository SalesUnitWrapperRepository;
        private ServiceWrapperRepository ServiceWrapperRepository;
        private TestFriendAddressWrapperRepository TestFriendAddressWrapperRepository;
        private TestFriendWrapperRepository TestFriendWrapperRepository;
        private TestFriendEmailWrapperRepository TestFriendEmailWrapperRepository;
        private TestFriendGroupWrapperRepository TestFriendGroupWrapperRepository;
        private DocumentWrapperRepository DocumentWrapperRepository;
        private TestEntityWrapperRepository TestEntityWrapperRepository;
        private TestHusbandWrapperRepository TestHusbandWrapperRepository;
        private TestWifeWrapperRepository TestWifeWrapperRepository;
        private TestChildWrapperRepository TestChildWrapperRepository;
        private SumOnDateWrapperRepository SumOnDateWrapperRepository;
        private ProductWrapperRepository ProductWrapperRepository;
        private OfferWrapperRepository OfferWrapperRepository;
        private EmployeeWrapperRepository EmployeeWrapperRepository;
        private OrderWrapperRepository OrderWrapperRepository;
        private PaymentConditionWrapperRepository PaymentConditionWrapperRepository;
        private PaymentDocumentWrapperRepository PaymentDocumentWrapperRepository;
        private FacilityWrapperRepository FacilityWrapperRepository;
        private ProjectWrapperRepository ProjectWrapperRepository;
        private UserRoleWrapperRepository UserRoleWrapperRepository;
        private SpecificationWrapperRepository SpecificationWrapperRepository;
        private TenderWrapperRepository TenderWrapperRepository;
        private TenderTypeWrapperRepository TenderTypeWrapperRepository;
        private UserWrapperRepository UserWrapperRepository;
    }
}
