using HVTApp.Model.POCOs;
using Prism.Events;

namespace HVTApp.Model.Events
{
	public partial class AfterSaveNotificationUnitEvent : PubSubEvent<NotificationUnit> { }
	public partial class AfterSaveCountryUnionEvent : PubSubEvent<CountryUnion> { }
	public partial class AfterSaveBudgetEvent : PubSubEvent<Budget> { }
	public partial class AfterSaveBudgetUnitEvent : PubSubEvent<BudgetUnit> { }
	public partial class AfterSaveConstructorParametersListEvent : PubSubEvent<ConstructorParametersList> { }
	public partial class AfterSaveConstructorsParametersEvent : PubSubEvent<ConstructorsParameters> { }
	public partial class AfterSaveCostsPercentsEvent : PubSubEvent<CostsPercents> { }
	public partial class AfterSaveCreateNewProductTaskEvent : PubSubEvent<CreateNewProductTask> { }
	public partial class AfterSaveInvoiceForPaymentTaskEvent : PubSubEvent<InvoiceForPaymentTask> { }
	public partial class AfterSaveTaskInvoiceForPaymentEvent : PubSubEvent<TaskInvoiceForPayment> { }
	public partial class AfterSaveTaskInvoiceForPaymentItemEvent : PubSubEvent<TaskInvoiceForPaymentItem> { }
	public partial class AfterSaveDesignDepartmentEvent : PubSubEvent<DesignDepartment> { }
	public partial class AfterSaveDirectumTaskEvent : PubSubEvent<DirectumTask> { }
	public partial class AfterSaveDirectumTaskGroupEvent : PubSubEvent<DirectumTaskGroup> { }
	public partial class AfterSaveDirectumTaskGroupFileEvent : PubSubEvent<DirectumTaskGroupFile> { }
	public partial class AfterSaveDirectumTaskMessageEvent : PubSubEvent<DirectumTaskMessage> { }
	public partial class AfterSaveDocumentNumberEvent : PubSubEvent<DocumentNumber> { }
	public partial class AfterSaveIncomingRequestEvent : PubSubEvent<IncomingRequest> { }
	public partial class AfterSaveLaborHourCostEvent : PubSubEvent<LaborHourCost> { }
	public partial class AfterSaveLaborHoursEvent : PubSubEvent<LaborHours> { }
	public partial class AfterSaveLogUnitEvent : PubSubEvent<LogUnit> { }
	public partial class AfterSaveLosingReasonEvent : PubSubEvent<LosingReason> { }
	public partial class AfterSaveMarketFieldEvent : PubSubEvent<MarketField> { }
	public partial class AfterSavePaymentActualEvent : PubSubEvent<PaymentActual> { }
	public partial class AfterSavePaymentConditionPointEvent : PubSubEvent<PaymentConditionPoint> { }
	public partial class AfterSavePaymentPlannedEvent : PubSubEvent<PaymentPlanned> { }
	public partial class AfterSavePenaltyEvent : PubSubEvent<Penalty> { }
	public partial class AfterSavePriceCalculationEvent : PubSubEvent<PriceCalculation> { }
	public partial class AfterSavePriceCalculationFileEvent : PubSubEvent<PriceCalculationFile> { }
	public partial class AfterSavePriceCalculationHistoryItemEvent : PubSubEvent<PriceCalculationHistoryItem> { }
	public partial class AfterSavePriceCalculationItemEvent : PubSubEvent<PriceCalculationItem> { }
	public partial class AfterSaveDesignDepartmentParametersEvent : PubSubEvent<DesignDepartmentParameters> { }
	public partial class AfterSaveDesignDepartmentParametersAddedBlocksEvent : PubSubEvent<DesignDepartmentParametersAddedBlocks> { }
	public partial class AfterSaveDesignDepartmentParametersSubTaskEvent : PubSubEvent<DesignDepartmentParametersSubTask> { }
	public partial class AfterSaveNotificationsReportsSettingsEvent : PubSubEvent<NotificationsReportsSettings> { }
	public partial class AfterSavePriceEngineeringTaskEvent : PubSubEvent<PriceEngineeringTask> { }
	public partial class AfterSavePriceEngineeringTaskFileAnswerEvent : PubSubEvent<PriceEngineeringTaskFileAnswer> { }
	public partial class AfterSavePriceEngineeringTaskFileTechnicalRequirementsEvent : PubSubEvent<PriceEngineeringTaskFileTechnicalRequirements> { }
	public partial class AfterSavePriceEngineeringTaskMessageEvent : PubSubEvent<PriceEngineeringTaskMessage> { }
	public partial class AfterSavePriceEngineeringTaskProductBlockAddedEvent : PubSubEvent<PriceEngineeringTaskProductBlockAdded> { }
	public partial class AfterSavePriceEngineeringTasksEvent : PubSubEvent<PriceEngineeringTasks> { }
	public partial class AfterSavePriceEngineeringTasksFileTechnicalRequirementsEvent : PubSubEvent<PriceEngineeringTasksFileTechnicalRequirements> { }
	public partial class AfterSavePriceEngineeringTaskStatusEvent : PubSubEvent<PriceEngineeringTaskStatus> { }
	public partial class AfterSaveStructureCostVersionEvent : PubSubEvent<StructureCostVersion> { }
	public partial class AfterSaveProductCategoryEvent : PubSubEvent<ProductCategory> { }
	public partial class AfterSaveProductCategoryPriceAndCostEvent : PubSubEvent<ProductCategoryPriceAndCost> { }
	public partial class AfterSaveProductIncludedEvent : PubSubEvent<ProductIncluded> { }
	public partial class AfterSaveProductDesignationEvent : PubSubEvent<ProductDesignation> { }
	public partial class AfterSaveProductTypeEvent : PubSubEvent<ProductType> { }
	public partial class AfterSaveProductTypeDesignationEvent : PubSubEvent<ProductTypeDesignation> { }
	public partial class AfterSaveProjectTypeEvent : PubSubEvent<ProjectType> { }
	public partial class AfterSaveStandartMarginalIncomeEvent : PubSubEvent<StandartMarginalIncome> { }
	public partial class AfterSaveStandartProductionTermEvent : PubSubEvent<StandartProductionTerm> { }
	public partial class AfterSaveStructureCostEvent : PubSubEvent<StructureCost> { }
	public partial class AfterSaveSupervisionEvent : PubSubEvent<Supervision> { }
	public partial class AfterSaveAnswerFileTceEvent : PubSubEvent<AnswerFileTce> { }
	public partial class AfterSaveShippingCostFileEvent : PubSubEvent<ShippingCostFile> { }
	public partial class AfterSaveTechnicalRequrementsEvent : PubSubEvent<TechnicalRequrements> { }
	public partial class AfterSaveTechnicalRequrementsFileEvent : PubSubEvent<TechnicalRequrementsFile> { }
	public partial class AfterSaveTechnicalRequrementsTaskEvent : PubSubEvent<TechnicalRequrementsTask> { }
	public partial class AfterSaveTechnicalRequrementsTaskHistoryElementEvent : PubSubEvent<TechnicalRequrementsTaskHistoryElement> { }
	public partial class AfterSaveUserGroupEvent : PubSubEvent<UserGroup> { }
	public partial class AfterSaveGlobalPropertiesEvent : PubSubEvent<GlobalProperties> { }
	public partial class AfterSaveAddressEvent : PubSubEvent<Address> { }
	public partial class AfterSaveCountryEvent : PubSubEvent<Country> { }
	public partial class AfterSaveDistrictEvent : PubSubEvent<District> { }
	public partial class AfterSaveLocalityEvent : PubSubEvent<Locality> { }
	public partial class AfterSaveLocalityTypeEvent : PubSubEvent<LocalityType> { }
	public partial class AfterSaveRegionEvent : PubSubEvent<Region> { }
	public partial class AfterSaveSumEvent : PubSubEvent<Sum> { }
	public partial class AfterSaveCurrencyExchangeRateEvent : PubSubEvent<CurrencyExchangeRate> { }
	public partial class AfterSaveNoteEvent : PubSubEvent<Note> { }
	public partial class AfterSaveOfferUnitEvent : PubSubEvent<OfferUnit> { }
	public partial class AfterSavePaymentConditionSetEvent : PubSubEvent<PaymentConditionSet> { }
	public partial class AfterSaveProductBlockEvent : PubSubEvent<ProductBlock> { }
	public partial class AfterSaveProductDependentEvent : PubSubEvent<ProductDependent> { }
	public partial class AfterSaveBankDetailsEvent : PubSubEvent<BankDetails> { }
	public partial class AfterSaveCompanyEvent : PubSubEvent<Company> { }
	public partial class AfterSaveCompanyFormEvent : PubSubEvent<CompanyForm> { }
	public partial class AfterSaveDocumentsRegistrationDetailsEvent : PubSubEvent<DocumentsRegistrationDetails> { }
	public partial class AfterSaveEmployeesPositionEvent : PubSubEvent<EmployeesPosition> { }
	public partial class AfterSaveFacilityTypeEvent : PubSubEvent<FacilityType> { }
	public partial class AfterSaveActivityFieldEvent : PubSubEvent<ActivityField> { }
	public partial class AfterSaveContractEvent : PubSubEvent<Contract> { }
	public partial class AfterSaveMeasureEvent : PubSubEvent<Measure> { }
	public partial class AfterSaveParameterEvent : PubSubEvent<Parameter> { }
	public partial class AfterSaveParameterGroupEvent : PubSubEvent<ParameterGroup> { }
	public partial class AfterSaveProductRelationEvent : PubSubEvent<ProductRelation> { }
	public partial class AfterSavePersonEvent : PubSubEvent<Person> { }
	public partial class AfterSaveParameterRelationEvent : PubSubEvent<ParameterRelation> { }
	public partial class AfterSaveSalesUnitEvent : PubSubEvent<SalesUnit> { }
	public partial class AfterSaveDocumentEvent : PubSubEvent<Document> { }
	public partial class AfterSaveSumOnDateEvent : PubSubEvent<SumOnDate> { }
	public partial class AfterSaveProductEvent : PubSubEvent<Product> { }
	public partial class AfterSaveOfferEvent : PubSubEvent<Offer> { }
	public partial class AfterSaveEmployeeEvent : PubSubEvent<Employee> { }
	public partial class AfterSaveOrderEvent : PubSubEvent<Order> { }
	public partial class AfterSavePaymentConditionEvent : PubSubEvent<PaymentCondition> { }
	public partial class AfterSavePaymentDocumentEvent : PubSubEvent<PaymentDocument> { }
	public partial class AfterSaveFacilityEvent : PubSubEvent<Facility> { }
	public partial class AfterSaveProjectEvent : PubSubEvent<Project> { }
	public partial class AfterSaveUserRoleEvent : PubSubEvent<UserRole> { }
	public partial class AfterSaveSpecificationEvent : PubSubEvent<Specification> { }
	public partial class AfterSaveTenderEvent : PubSubEvent<Tender> { }
	public partial class AfterSaveTenderTypeEvent : PubSubEvent<TenderType> { }
	public partial class AfterSaveUserEvent : PubSubEvent<User> { }
}
