using HVTApp.Model.POCOs;
using Prism.Events;

namespace HVTApp.Model.Events
{
	public partial class AfterSelectCountryUnionEvent : PubSubEvent<PubSubEventArgs<CountryUnion>> { }
	public partial class AfterSelectBankGuaranteeEvent : PubSubEvent<PubSubEventArgs<BankGuarantee>> { }
	public partial class AfterSelectBankGuaranteeTypeEvent : PubSubEvent<PubSubEventArgs<BankGuaranteeType>> { }
	public partial class AfterSelectConstructorParametersListEvent : PubSubEvent<PubSubEventArgs<ConstructorParametersList>> { }
	public partial class AfterSelectConstructorsParametersEvent : PubSubEvent<PubSubEventArgs<ConstructorsParameters>> { }
	public partial class AfterSelectCreateNewProductTaskEvent : PubSubEvent<PubSubEventArgs<CreateNewProductTask>> { }
	public partial class AfterSelectDirectumTaskEvent : PubSubEvent<PubSubEventArgs<DirectumTask>> { }
	public partial class AfterSelectDirectumTaskRouteEvent : PubSubEvent<PubSubEventArgs<DirectumTaskRoute>> { }
	public partial class AfterSelectDirectumTaskRouteItemEvent : PubSubEvent<PubSubEventArgs<DirectumTaskRouteItem>> { }
	public partial class AfterSelectDirectumTaskRouteItemMessageEvent : PubSubEvent<PubSubEventArgs<DirectumTaskRouteItemMessage>> { }
	public partial class AfterSelectDocumentNumberEvent : PubSubEvent<PubSubEventArgs<DocumentNumber>> { }
	public partial class AfterSelectFakeDataEvent : PubSubEvent<PubSubEventArgs<FakeData>> { }
	public partial class AfterSelectIncomingRequestEvent : PubSubEvent<PubSubEventArgs<IncomingRequest>> { }
	public partial class AfterSelectLosingReasonEvent : PubSubEvent<PubSubEventArgs<LosingReason>> { }
	public partial class AfterSelectMarketFieldEvent : PubSubEvent<PubSubEventArgs<MarketField>> { }
	public partial class AfterSelectPaymentActualEvent : PubSubEvent<PubSubEventArgs<PaymentActual>> { }
	public partial class AfterSelectPaymentConditionPointEvent : PubSubEvent<PubSubEventArgs<PaymentConditionPoint>> { }
	public partial class AfterSelectPaymentPlannedEvent : PubSubEvent<PubSubEventArgs<PaymentPlanned>> { }
	public partial class AfterSelectPenaltyEvent : PubSubEvent<PubSubEventArgs<Penalty>> { }
	public partial class AfterSelectPriceCalculationEvent : PubSubEvent<PubSubEventArgs<PriceCalculation>> { }
	public partial class AfterSelectPriceCalculationItemEvent : PubSubEvent<PubSubEventArgs<PriceCalculationItem>> { }
	public partial class AfterSelectProductIncludedEvent : PubSubEvent<PubSubEventArgs<ProductIncluded>> { }
	public partial class AfterSelectProductDesignationEvent : PubSubEvent<PubSubEventArgs<ProductDesignation>> { }
	public partial class AfterSelectProductTypeEvent : PubSubEvent<PubSubEventArgs<ProductType>> { }
	public partial class AfterSelectProductTypeDesignationEvent : PubSubEvent<PubSubEventArgs<ProductTypeDesignation>> { }
	public partial class AfterSelectProjectTypeEvent : PubSubEvent<PubSubEventArgs<ProjectType>> { }
	public partial class AfterSelectStandartMarginalIncomeEvent : PubSubEvent<PubSubEventArgs<StandartMarginalIncome>> { }
	public partial class AfterSelectStandartProductionTermEvent : PubSubEvent<PubSubEventArgs<StandartProductionTerm>> { }
	public partial class AfterSelectStructureCostEvent : PubSubEvent<PubSubEventArgs<StructureCost>> { }
	public partial class AfterSelectGlobalPropertiesEvent : PubSubEvent<PubSubEventArgs<GlobalProperties>> { }
	public partial class AfterSelectAddressEvent : PubSubEvent<PubSubEventArgs<Address>> { }
	public partial class AfterSelectCountryEvent : PubSubEvent<PubSubEventArgs<Country>> { }
	public partial class AfterSelectDistrictEvent : PubSubEvent<PubSubEventArgs<District>> { }
	public partial class AfterSelectLocalityEvent : PubSubEvent<PubSubEventArgs<Locality>> { }
	public partial class AfterSelectLocalityTypeEvent : PubSubEvent<PubSubEventArgs<LocalityType>> { }
	public partial class AfterSelectRegionEvent : PubSubEvent<PubSubEventArgs<Region>> { }
	public partial class AfterSelectSumEvent : PubSubEvent<PubSubEventArgs<Sum>> { }
	public partial class AfterSelectCurrencyExchangeRateEvent : PubSubEvent<PubSubEventArgs<CurrencyExchangeRate>> { }
	public partial class AfterSelectNoteEvent : PubSubEvent<PubSubEventArgs<Note>> { }
	public partial class AfterSelectOfferUnitEvent : PubSubEvent<PubSubEventArgs<OfferUnit>> { }
	public partial class AfterSelectPaymentConditionSetEvent : PubSubEvent<PubSubEventArgs<PaymentConditionSet>> { }
	public partial class AfterSelectProductBlockEvent : PubSubEvent<PubSubEventArgs<ProductBlock>> { }
	public partial class AfterSelectProductDependentEvent : PubSubEvent<PubSubEventArgs<ProductDependent>> { }
	public partial class AfterSelectBankDetailsEvent : PubSubEvent<PubSubEventArgs<BankDetails>> { }
	public partial class AfterSelectCompanyEvent : PubSubEvent<PubSubEventArgs<Company>> { }
	public partial class AfterSelectCompanyFormEvent : PubSubEvent<PubSubEventArgs<CompanyForm>> { }
	public partial class AfterSelectDocumentsRegistrationDetailsEvent : PubSubEvent<PubSubEventArgs<DocumentsRegistrationDetails>> { }
	public partial class AfterSelectEmployeesPositionEvent : PubSubEvent<PubSubEventArgs<EmployeesPosition>> { }
	public partial class AfterSelectFacilityTypeEvent : PubSubEvent<PubSubEventArgs<FacilityType>> { }
	public partial class AfterSelectActivityFieldEvent : PubSubEvent<PubSubEventArgs<ActivityField>> { }
	public partial class AfterSelectContractEvent : PubSubEvent<PubSubEventArgs<Contract>> { }
	public partial class AfterSelectMeasureEvent : PubSubEvent<PubSubEventArgs<Measure>> { }
	public partial class AfterSelectParameterEvent : PubSubEvent<PubSubEventArgs<Parameter>> { }
	public partial class AfterSelectParameterGroupEvent : PubSubEvent<PubSubEventArgs<ParameterGroup>> { }
	public partial class AfterSelectProductRelationEvent : PubSubEvent<PubSubEventArgs<ProductRelation>> { }
	public partial class AfterSelectPersonEvent : PubSubEvent<PubSubEventArgs<Person>> { }
	public partial class AfterSelectParameterRelationEvent : PubSubEvent<PubSubEventArgs<ParameterRelation>> { }
	public partial class AfterSelectSalesUnitEvent : PubSubEvent<PubSubEventArgs<SalesUnit>> { }
	public partial class AfterSelectDocumentEvent : PubSubEvent<PubSubEventArgs<Document>> { }
	public partial class AfterSelectSumOnDateEvent : PubSubEvent<PubSubEventArgs<SumOnDate>> { }
	public partial class AfterSelectProductEvent : PubSubEvent<PubSubEventArgs<Product>> { }
	public partial class AfterSelectOfferEvent : PubSubEvent<PubSubEventArgs<Offer>> { }
	public partial class AfterSelectEmployeeEvent : PubSubEvent<PubSubEventArgs<Employee>> { }
	public partial class AfterSelectOrderEvent : PubSubEvent<PubSubEventArgs<Order>> { }
	public partial class AfterSelectPaymentConditionEvent : PubSubEvent<PubSubEventArgs<PaymentCondition>> { }
	public partial class AfterSelectPaymentDocumentEvent : PubSubEvent<PubSubEventArgs<PaymentDocument>> { }
	public partial class AfterSelectFacilityEvent : PubSubEvent<PubSubEventArgs<Facility>> { }
	public partial class AfterSelectProjectEvent : PubSubEvent<PubSubEventArgs<Project>> { }
	public partial class AfterSelectUserRoleEvent : PubSubEvent<PubSubEventArgs<UserRole>> { }
	public partial class AfterSelectSpecificationEvent : PubSubEvent<PubSubEventArgs<Specification>> { }
	public partial class AfterSelectTenderEvent : PubSubEvent<PubSubEventArgs<Tender>> { }
	public partial class AfterSelectTenderTypeEvent : PubSubEvent<PubSubEventArgs<TenderType>> { }
	public partial class AfterSelectUserEvent : PubSubEvent<PubSubEventArgs<User>> { }
}
