using HVTApp.Model.POCOs;
using Prism.Events;

namespace HVTApp.Model.Events
{
	public partial class AfterRemoveNotificationUnitEvent : PubSubEvent<NotificationUnit> { }
	public partial class AfterRemoveCountryUnionEvent : PubSubEvent<CountryUnion> { }
	public partial class AfterRemoveBudgetEvent : PubSubEvent<Budget> { }
	public partial class AfterRemoveBudgetUnitEvent : PubSubEvent<BudgetUnit> { }
	public partial class AfterRemoveConstructorParametersListEvent : PubSubEvent<ConstructorParametersList> { }
	public partial class AfterRemoveConstructorsParametersEvent : PubSubEvent<ConstructorsParameters> { }
	public partial class AfterRemoveCostsPercentsEvent : PubSubEvent<CostsPercents> { }
	public partial class AfterRemoveCreateNewProductTaskEvent : PubSubEvent<CreateNewProductTask> { }
	public partial class AfterRemoveDesignDepartmentEvent : PubSubEvent<DesignDepartment> { }
	public partial class AfterRemoveDirectumTaskEvent : PubSubEvent<DirectumTask> { }
	public partial class AfterRemoveDirectumTaskGroupEvent : PubSubEvent<DirectumTaskGroup> { }
	public partial class AfterRemoveDirectumTaskGroupFileEvent : PubSubEvent<DirectumTaskGroupFile> { }
	public partial class AfterRemoveDirectumTaskMessageEvent : PubSubEvent<DirectumTaskMessage> { }
	public partial class AfterRemoveDocumentNumberEvent : PubSubEvent<DocumentNumber> { }
	public partial class AfterRemoveIncomingRequestEvent : PubSubEvent<IncomingRequest> { }
	public partial class AfterRemoveLaborHourCostEvent : PubSubEvent<LaborHourCost> { }
	public partial class AfterRemoveLaborHoursEvent : PubSubEvent<LaborHours> { }
	public partial class AfterRemoveLogUnitEvent : PubSubEvent<LogUnit> { }
	public partial class AfterRemoveLosingReasonEvent : PubSubEvent<LosingReason> { }
	public partial class AfterRemoveMarketFieldEvent : PubSubEvent<MarketField> { }
	public partial class AfterRemovePaymentActualEvent : PubSubEvent<PaymentActual> { }
	public partial class AfterRemovePaymentConditionPointEvent : PubSubEvent<PaymentConditionPoint> { }
	public partial class AfterRemovePaymentPlannedEvent : PubSubEvent<PaymentPlanned> { }
	public partial class AfterRemovePenaltyEvent : PubSubEvent<Penalty> { }
	public partial class AfterRemovePriceCalculationEvent : PubSubEvent<PriceCalculation> { }
	public partial class AfterRemovePriceCalculationFileEvent : PubSubEvent<PriceCalculationFile> { }
	public partial class AfterRemovePriceCalculationHistoryItemEvent : PubSubEvent<PriceCalculationHistoryItem> { }
	public partial class AfterRemovePriceCalculationItemEvent : PubSubEvent<PriceCalculationItem> { }
	public partial class AfterRemoveDesignDepartmentParametersEvent : PubSubEvent<DesignDepartmentParameters> { }
	public partial class AfterRemoveDesignDepartmentParametersAddedBlocksEvent : PubSubEvent<DesignDepartmentParametersAddedBlocks> { }
	public partial class AfterRemoveDesignDepartmentParametersSubTaskEvent : PubSubEvent<DesignDepartmentParametersSubTask> { }
	public partial class AfterRemoveNotificationsReportsSettingsEvent : PubSubEvent<NotificationsReportsSettings> { }
	public partial class AfterRemovePriceEngineeringTaskEvent : PubSubEvent<PriceEngineeringTask> { }
	public partial class AfterRemovePriceEngineeringTaskFileAnswerEvent : PubSubEvent<PriceEngineeringTaskFileAnswer> { }
	public partial class AfterRemovePriceEngineeringTaskFileTechnicalRequirementsEvent : PubSubEvent<PriceEngineeringTaskFileTechnicalRequirements> { }
	public partial class AfterRemovePriceEngineeringTaskMessageEvent : PubSubEvent<PriceEngineeringTaskMessage> { }
	public partial class AfterRemovePriceEngineeringTaskProductBlockAddedEvent : PubSubEvent<PriceEngineeringTaskProductBlockAdded> { }
	public partial class AfterRemovePriceEngineeringTasksEvent : PubSubEvent<PriceEngineeringTasks> { }
	public partial class AfterRemovePriceEngineeringTasksFileTechnicalRequirementsEvent : PubSubEvent<PriceEngineeringTasksFileTechnicalRequirements> { }
	public partial class AfterRemovePriceEngineeringTaskStatusEvent : PubSubEvent<PriceEngineeringTaskStatus> { }
	public partial class AfterRemoveStructureCostVersionEvent : PubSubEvent<StructureCostVersion> { }
	public partial class AfterRemoveProductCategoryEvent : PubSubEvent<ProductCategory> { }
	public partial class AfterRemoveProductCategoryPriceAndCostEvent : PubSubEvent<ProductCategoryPriceAndCost> { }
	public partial class AfterRemoveProductIncludedEvent : PubSubEvent<ProductIncluded> { }
	public partial class AfterRemoveProductDesignationEvent : PubSubEvent<ProductDesignation> { }
	public partial class AfterRemoveProductTypeEvent : PubSubEvent<ProductType> { }
	public partial class AfterRemoveProductTypeDesignationEvent : PubSubEvent<ProductTypeDesignation> { }
	public partial class AfterRemoveProjectTypeEvent : PubSubEvent<ProjectType> { }
	public partial class AfterRemoveStandartMarginalIncomeEvent : PubSubEvent<StandartMarginalIncome> { }
	public partial class AfterRemoveStandartProductionTermEvent : PubSubEvent<StandartProductionTerm> { }
	public partial class AfterRemoveStructureCostEvent : PubSubEvent<StructureCost> { }
	public partial class AfterRemoveSupervisionEvent : PubSubEvent<Supervision> { }
	public partial class AfterRemoveTaskInvoiceForPaymentEvent : PubSubEvent<TaskInvoiceForPayment> { }
	public partial class AfterRemoveTaskInvoiceForPaymentItemEvent : PubSubEvent<TaskInvoiceForPaymentItem> { }
	public partial class AfterRemoveAnswerFileTceEvent : PubSubEvent<AnswerFileTce> { }
	public partial class AfterRemoveShippingCostFileEvent : PubSubEvent<ShippingCostFile> { }
	public partial class AfterRemoveTechnicalRequrementsEvent : PubSubEvent<TechnicalRequrements> { }
	public partial class AfterRemoveTechnicalRequrementsFileEvent : PubSubEvent<TechnicalRequrementsFile> { }
	public partial class AfterRemoveTechnicalRequrementsTaskEvent : PubSubEvent<TechnicalRequrementsTask> { }
	public partial class AfterRemoveTechnicalRequrementsTaskHistoryElementEvent : PubSubEvent<TechnicalRequrementsTaskHistoryElement> { }
	public partial class AfterRemoveUserGroupEvent : PubSubEvent<UserGroup> { }
	public partial class AfterRemoveGlobalPropertiesEvent : PubSubEvent<GlobalProperties> { }
	public partial class AfterRemoveAddressEvent : PubSubEvent<Address> { }
	public partial class AfterRemoveCountryEvent : PubSubEvent<Country> { }
	public partial class AfterRemoveDistrictEvent : PubSubEvent<District> { }
	public partial class AfterRemoveLocalityEvent : PubSubEvent<Locality> { }
	public partial class AfterRemoveLocalityTypeEvent : PubSubEvent<LocalityType> { }
	public partial class AfterRemoveRegionEvent : PubSubEvent<Region> { }
	public partial class AfterRemoveSumEvent : PubSubEvent<Sum> { }
	public partial class AfterRemoveCurrencyExchangeRateEvent : PubSubEvent<CurrencyExchangeRate> { }
	public partial class AfterRemoveNoteEvent : PubSubEvent<Note> { }
	public partial class AfterRemoveOfferUnitEvent : PubSubEvent<OfferUnit> { }
	public partial class AfterRemovePaymentConditionSetEvent : PubSubEvent<PaymentConditionSet> { }
	public partial class AfterRemoveProductBlockEvent : PubSubEvent<ProductBlock> { }
	public partial class AfterRemoveProductDependentEvent : PubSubEvent<ProductDependent> { }
	public partial class AfterRemoveBankDetailsEvent : PubSubEvent<BankDetails> { }
	public partial class AfterRemoveCompanyEvent : PubSubEvent<Company> { }
	public partial class AfterRemoveCompanyFormEvent : PubSubEvent<CompanyForm> { }
	public partial class AfterRemoveDocumentsRegistrationDetailsEvent : PubSubEvent<DocumentsRegistrationDetails> { }
	public partial class AfterRemoveEmployeesPositionEvent : PubSubEvent<EmployeesPosition> { }
	public partial class AfterRemoveFacilityTypeEvent : PubSubEvent<FacilityType> { }
	public partial class AfterRemoveActivityFieldEvent : PubSubEvent<ActivityField> { }
	public partial class AfterRemoveContractEvent : PubSubEvent<Contract> { }
	public partial class AfterRemoveMeasureEvent : PubSubEvent<Measure> { }
	public partial class AfterRemoveParameterEvent : PubSubEvent<Parameter> { }
	public partial class AfterRemoveParameterGroupEvent : PubSubEvent<ParameterGroup> { }
	public partial class AfterRemoveProductRelationEvent : PubSubEvent<ProductRelation> { }
	public partial class AfterRemovePersonEvent : PubSubEvent<Person> { }
	public partial class AfterRemoveParameterRelationEvent : PubSubEvent<ParameterRelation> { }
	public partial class AfterRemoveSalesUnitEvent : PubSubEvent<SalesUnit> { }
	public partial class AfterRemoveDocumentEvent : PubSubEvent<Document> { }
	public partial class AfterRemoveSumOnDateEvent : PubSubEvent<SumOnDate> { }
	public partial class AfterRemoveProductEvent : PubSubEvent<Product> { }
	public partial class AfterRemoveOfferEvent : PubSubEvent<Offer> { }
	public partial class AfterRemoveEmployeeEvent : PubSubEvent<Employee> { }
	public partial class AfterRemoveOrderEvent : PubSubEvent<Order> { }
	public partial class AfterRemovePaymentConditionEvent : PubSubEvent<PaymentCondition> { }
	public partial class AfterRemovePaymentDocumentEvent : PubSubEvent<PaymentDocument> { }
	public partial class AfterRemoveFacilityEvent : PubSubEvent<Facility> { }
	public partial class AfterRemoveProjectEvent : PubSubEvent<Project> { }
	public partial class AfterRemoveUserRoleEvent : PubSubEvent<UserRole> { }
	public partial class AfterRemoveSpecificationEvent : PubSubEvent<Specification> { }
	public partial class AfterRemoveTenderEvent : PubSubEvent<Tender> { }
	public partial class AfterRemoveTenderTypeEvent : PubSubEvent<TenderType> { }
	public partial class AfterRemoveUserEvent : PubSubEvent<User> { }
}
