using HVTApp.Model.POCOs;
using Prism.Events;

namespace HVTApp.Model.Events
{
	public partial class AfterSelectCountryUnionEvent : PubSubEvent<PubSubEventArgs<CountryUnion>> { }
	public partial class AfterSelectBankGuaranteeEvent : PubSubEvent<PubSubEventArgs<BankGuarantee>> { }
	public partial class AfterSelectBankGuaranteeTypeEvent : PubSubEvent<PubSubEventArgs<BankGuaranteeType>> { }
	public partial class AfterSelectBudgetEvent : PubSubEvent<PubSubEventArgs<Budget>> { }
	public partial class AfterSelectBudgetUnitEvent : PubSubEvent<PubSubEventArgs<BudgetUnit>> { }
	public partial class AfterSelectConstructorParametersListEvent : PubSubEvent<PubSubEventArgs<ConstructorParametersList>> { }
	public partial class AfterSelectConstructorsParametersEvent : PubSubEvent<PubSubEventArgs<ConstructorsParameters>> { }
	public partial class AfterSelectCostsPercentsEvent : PubSubEvent<PubSubEventArgs<CostsPercents>> { }
	public partial class AfterSelectCreateNewProductTaskEvent : PubSubEvent<PubSubEventArgs<CreateNewProductTask>> { }
	public partial class AfterSelectDesignDepartmentEvent : PubSubEvent<PubSubEventArgs<DesignDepartment>> { }
	public partial class AfterSelectDirectumTaskEvent : PubSubEvent<PubSubEventArgs<DirectumTask>> { }
	public partial class AfterSelectDirectumTaskGroupEvent : PubSubEvent<PubSubEventArgs<DirectumTaskGroup>> { }
	public partial class AfterSelectDirectumTaskGroupFileEvent : PubSubEvent<PubSubEventArgs<DirectumTaskGroupFile>> { }
	public partial class AfterSelectDirectumTaskMessageEvent : PubSubEvent<PubSubEventArgs<DirectumTaskMessage>> { }
	public partial class AfterSelectDocumentNumberEvent : PubSubEvent<PubSubEventArgs<DocumentNumber>> { }
	public partial class AfterSelectEventServiceUnitEvent : PubSubEvent<PubSubEventArgs<EventServiceUnit>> { }
	public partial class AfterSelectIncomingRequestEvent : PubSubEvent<PubSubEventArgs<IncomingRequest>> { }
	public partial class AfterSelectLaborHourCostEvent : PubSubEvent<PubSubEventArgs<LaborHourCost>> { }
	public partial class AfterSelectLaborHoursEvent : PubSubEvent<PubSubEventArgs<LaborHours>> { }
	public partial class AfterSelectLogUnitEvent : PubSubEvent<PubSubEventArgs<LogUnit>> { }
	public partial class AfterSelectLosingReasonEvent : PubSubEvent<PubSubEventArgs<LosingReason>> { }
	public partial class AfterSelectMarketFieldEvent : PubSubEvent<PubSubEventArgs<MarketField>> { }
	public partial class AfterSelectPaymentActualEvent : PubSubEvent<PubSubEventArgs<PaymentActual>> { }
	public partial class AfterSelectPaymentConditionPointEvent : PubSubEvent<PubSubEventArgs<PaymentConditionPoint>> { }
	public partial class AfterSelectPaymentPlannedEvent : PubSubEvent<PubSubEventArgs<PaymentPlanned>> { }
	public partial class AfterSelectPenaltyEvent : PubSubEvent<PubSubEventArgs<Penalty>> { }
	public partial class AfterSelectPriceCalculationEvent : PubSubEvent<PubSubEventArgs<PriceCalculation>> { }
	public partial class AfterSelectPriceCalculationFileEvent : PubSubEvent<PubSubEventArgs<PriceCalculationFile>> { }
	public partial class AfterSelectPriceCalculationHistoryItemEvent : PubSubEvent<PubSubEventArgs<PriceCalculationHistoryItem>> { }
	public partial class AfterSelectPriceCalculationItemEvent : PubSubEvent<PubSubEventArgs<PriceCalculationItem>> { }
	public partial class AfterSelectDesignDepartmentParametersEvent : PubSubEvent<PubSubEventArgs<DesignDepartmentParameters>> { }
	public partial class AfterSelectPriceEngineeringTaskEvent : PubSubEvent<PubSubEventArgs<PriceEngineeringTask>> { }
	public partial class AfterSelectPriceEngineeringTaskFileAnswerEvent : PubSubEvent<PubSubEventArgs<PriceEngineeringTaskFileAnswer>> { }
	public partial class AfterSelectPriceEngineeringTaskFileTechnicalRequirementsEvent : PubSubEvent<PubSubEventArgs<PriceEngineeringTaskFileTechnicalRequirements>> { }
	public partial class AfterSelectPriceEngineeringTaskMessageEvent : PubSubEvent<PubSubEventArgs<PriceEngineeringTaskMessage>> { }
	public partial class AfterSelectPriceEngineeringTaskProductBlockAddedEvent : PubSubEvent<PubSubEventArgs<PriceEngineeringTaskProductBlockAdded>> { }
	public partial class AfterSelectPriceEngineeringTaskStatusEvent : PubSubEvent<PubSubEventArgs<PriceEngineeringTaskStatus>> { }
	public partial class AfterSelectProductCategoryEvent : PubSubEvent<PubSubEventArgs<ProductCategory>> { }
	public partial class AfterSelectProductCategoryPriceAndCostEvent : PubSubEvent<PubSubEventArgs<ProductCategoryPriceAndCost>> { }
	public partial class AfterSelectProductIncludedEvent : PubSubEvent<PubSubEventArgs<ProductIncluded>> { }
	public partial class AfterSelectProductDesignationEvent : PubSubEvent<PubSubEventArgs<ProductDesignation>> { }
	public partial class AfterSelectProductTypeEvent : PubSubEvent<PubSubEventArgs<ProductType>> { }
	public partial class AfterSelectProductTypeDesignationEvent : PubSubEvent<PubSubEventArgs<ProductTypeDesignation>> { }
	public partial class AfterSelectProjectTypeEvent : PubSubEvent<PubSubEventArgs<ProjectType>> { }
	public partial class AfterSelectStandartMarginalIncomeEvent : PubSubEvent<PubSubEventArgs<StandartMarginalIncome>> { }
	public partial class AfterSelectStandartProductionTermEvent : PubSubEvent<PubSubEventArgs<StandartProductionTerm>> { }
	public partial class AfterSelectStructureCostEvent : PubSubEvent<PubSubEventArgs<StructureCost>> { }
	public partial class AfterSelectSupervisionEvent : PubSubEvent<PubSubEventArgs<Supervision>> { }
	public partial class AfterSelectAnswerFileTceEvent : PubSubEvent<PubSubEventArgs<AnswerFileTce>> { }
	public partial class AfterSelectShippingCostFileEvent : PubSubEvent<PubSubEventArgs<ShippingCostFile>> { }
	public partial class AfterSelectTechnicalRequrementsEvent : PubSubEvent<PubSubEventArgs<TechnicalRequrements>> { }
	public partial class AfterSelectTechnicalRequrementsFileEvent : PubSubEvent<PubSubEventArgs<TechnicalRequrementsFile>> { }
	public partial class AfterSelectTechnicalRequrementsTaskEvent : PubSubEvent<PubSubEventArgs<TechnicalRequrementsTask>> { }
	public partial class AfterSelectTechnicalRequrementsTaskHistoryElementEvent : PubSubEvent<PubSubEventArgs<TechnicalRequrementsTaskHistoryElement>> { }
	public partial class AfterSelectUserGroupEvent : PubSubEvent<PubSubEventArgs<UserGroup>> { }
	public partial class AfterSelectGlobalPropertiesEvent : PubSubEvent<PubSubEventArgs<GlobalProperties>> { }
	public partial class AfterSelectAddressEvent : PubSubEvent<PubSubEventArgs<Address>> { }
	public partial class AfterSelectCountryEvent : PubSubEvent<PubSubEventArgs<Country>> { }
	public partial class AfterSelectDistrictEvent : PubSubEvent<PubSubEventArgs<District>> { }
	public partial class AfterSelectLocalityEvent : PubSubEvent<PubSubEventArgs<Locality>> { }
	public partial class AfterSelectLocalityTypeEvent : PubSubEvent<PubSubEventArgs<LocalityType>> { }
	public partial class AfterSelectRegionEvent : PubSubEvent<PubSubEventArgs<Region>> { }
	public partial class AfterSelectSumEvent : PubSubEvent<PubSubEventArgs<Sum>> { }
	public partial class AfterSelectCurrencyExchangeRateEvent : PubSubEvent<PubSubEventArgs<CurrencyExchangeRate>> { }
	public partial class AfterSelectNoteEvent : PubSubEvent<PubSubEventArgs<Note>> { }
	public partial class AfterSelectOfferUnitEvent : PubSubEvent<PubSubEventArgs<OfferUnit>> { }
	public partial class AfterSelectPaymentConditionSetEvent : PubSubEvent<PubSubEventArgs<PaymentConditionSet>> { }
	public partial class AfterSelectProductBlockEvent : PubSubEvent<PubSubEventArgs<ProductBlock>> { }
	public partial class AfterSelectProductDependentEvent : PubSubEvent<PubSubEventArgs<ProductDependent>> { }
	public partial class AfterSelectBankDetailsEvent : PubSubEvent<PubSubEventArgs<BankDetails>> { }
	public partial class AfterSelectCompanyEvent : PubSubEvent<PubSubEventArgs<Company>> { }
	public partial class AfterSelectCompanyFormEvent : PubSubEvent<PubSubEventArgs<CompanyForm>> { }
	public partial class AfterSelectDocumentsRegistrationDetailsEvent : PubSubEvent<PubSubEventArgs<DocumentsRegistrationDetails>> { }
	public partial class AfterSelectEmployeesPositionEvent : PubSubEvent<PubSubEventArgs<EmployeesPosition>> { }
	public partial class AfterSelectFacilityTypeEvent : PubSubEvent<PubSubEventArgs<FacilityType>> { }
	public partial class AfterSelectActivityFieldEvent : PubSubEvent<PubSubEventArgs<ActivityField>> { }
	public partial class AfterSelectContractEvent : PubSubEvent<PubSubEventArgs<Contract>> { }
	public partial class AfterSelectMeasureEvent : PubSubEvent<PubSubEventArgs<Measure>> { }
	public partial class AfterSelectParameterEvent : PubSubEvent<PubSubEventArgs<Parameter>> { }
	public partial class AfterSelectParameterGroupEvent : PubSubEvent<PubSubEventArgs<ParameterGroup>> { }
	public partial class AfterSelectProductRelationEvent : PubSubEvent<PubSubEventArgs<ProductRelation>> { }
	public partial class AfterSelectPersonEvent : PubSubEvent<PubSubEventArgs<Person>> { }
	public partial class AfterSelectParameterRelationEvent : PubSubEvent<PubSubEventArgs<ParameterRelation>> { }
	public partial class AfterSelectSalesUnitEvent : PubSubEvent<PubSubEventArgs<SalesUnit>> { }
	public partial class AfterSelectDocumentEvent : PubSubEvent<PubSubEventArgs<Document>> { }
	public partial class AfterSelectSumOnDateEvent : PubSubEvent<PubSubEventArgs<SumOnDate>> { }
	public partial class AfterSelectProductEvent : PubSubEvent<PubSubEventArgs<Product>> { }
	public partial class AfterSelectOfferEvent : PubSubEvent<PubSubEventArgs<Offer>> { }
	public partial class AfterSelectEmployeeEvent : PubSubEvent<PubSubEventArgs<Employee>> { }
	public partial class AfterSelectOrderEvent : PubSubEvent<PubSubEventArgs<Order>> { }
	public partial class AfterSelectPaymentConditionEvent : PubSubEvent<PubSubEventArgs<PaymentCondition>> { }
	public partial class AfterSelectPaymentDocumentEvent : PubSubEvent<PubSubEventArgs<PaymentDocument>> { }
	public partial class AfterSelectFacilityEvent : PubSubEvent<PubSubEventArgs<Facility>> { }
	public partial class AfterSelectProjectEvent : PubSubEvent<PubSubEventArgs<Project>> { }
	public partial class AfterSelectUserRoleEvent : PubSubEvent<PubSubEventArgs<UserRole>> { }
	public partial class AfterSelectSpecificationEvent : PubSubEvent<PubSubEventArgs<Specification>> { }
	public partial class AfterSelectTenderEvent : PubSubEvent<PubSubEventArgs<Tender>> { }
	public partial class AfterSelectTenderTypeEvent : PubSubEvent<PubSubEventArgs<TenderType>> { }
	public partial class AfterSelectUserEvent : PubSubEvent<PubSubEventArgs<User>> { }
}
