namespace HVTApp.UI.Lookup
{
	public interface IAddressLookupDataService : ILookupDataService<AddressLookup> { } 
	public interface ICountryLookupDataService : ILookupDataService<CountryLookup> { } 
	public interface IDistrictLookupDataService : ILookupDataService<DistrictLookup> { } 
	public interface ILocalityLookupDataService : ILookupDataService<LocalityLookup> { } 
	public interface ILocalityTypeLookupDataService : ILookupDataService<LocalityTypeLookup> { } 
	public interface IRegionLookupDataService : ILookupDataService<RegionLookup> { } 
	public interface IAdditionalSalesUnitsLookupDataService : ILookupDataService<AdditionalSalesUnitsLookup> { } 
	public interface IBankDetailsLookupDataService : ILookupDataService<BankDetailsLookup> { } 
	public interface ICompanyLookupDataService : ILookupDataService<CompanyLookup> { } 
	public interface ICompanyFormLookupDataService : ILookupDataService<CompanyFormLookup> { } 
	public interface IDocumentsRegistrationDetailsLookupDataService : ILookupDataService<DocumentsRegistrationDetailsLookup> { } 
	public interface IEmployeesPositionLookupDataService : ILookupDataService<EmployeesPositionLookup> { } 
	public interface IFacilityTypeLookupDataService : ILookupDataService<FacilityTypeLookup> { } 
	public interface IActivityFieldLookupDataService : ILookupDataService<ActivityFieldLookup> { } 
	public interface IContractLookupDataService : ILookupDataService<ContractLookup> { } 
	public interface IMeasureLookupDataService : ILookupDataService<MeasureLookup> { } 
	public interface IParameterLookupDataService : ILookupDataService<ParameterLookup> { } 
	public interface IParameterGroupLookupDataService : ILookupDataService<ParameterGroupLookup> { } 
	public interface IProductRelationLookupDataService : ILookupDataService<ProductRelationLookup> { } 
	public interface IStandartPaymentConditionsLookupDataService : ILookupDataService<StandartPaymentConditionsLookup> { } 
	public interface IPersonLookupDataService : ILookupDataService<PersonLookup> { } 
	public interface IPaymentPlannedLookupDataService : ILookupDataService<PaymentPlannedLookup> { } 
	public interface IPaymentActualLookupDataService : ILookupDataService<PaymentActualLookup> { } 
	public interface IParameterRelationLookupDataService : ILookupDataService<ParameterRelationLookup> { } 
	public interface IProjectUnitLookupDataService : ILookupDataService<ProjectUnitLookup> { } 
	public interface IShipmentUnitLookupDataService : ILookupDataService<ShipmentUnitLookup> { } 
	public interface IProductionUnitLookupDataService : ILookupDataService<ProductionUnitLookup> { } 
	public interface ISalesUnitLookupDataService : ILookupDataService<SalesUnitLookup> { } 
	public interface ITestFriendAddressLookupDataService : ILookupDataService<TestFriendAddressLookup> { } 
	public interface ITestFriendLookupDataService : ILookupDataService<TestFriendLookup> { } 
	public interface ITestFriendEmailLookupDataService : ILookupDataService<TestFriendEmailLookup> { } 
	public interface ITestFriendGroupLookupDataService : ILookupDataService<TestFriendGroupLookup> { } 
	public interface IDocumentLookupDataService : ILookupDataService<DocumentLookup> { } 
	public interface ITestEntityLookupDataService : ILookupDataService<TestEntityLookup> { } 
	public interface ITestHusbandLookupDataService : ILookupDataService<TestHusbandLookup> { } 
	public interface ITestWifeLookupDataService : ILookupDataService<TestWifeLookup> { } 
	public interface ITestChildLookupDataService : ILookupDataService<TestChildLookup> { } 
	public interface ICostOnDateLookupDataService : ILookupDataService<CostOnDateLookup> { } 
	public interface ICostLookupDataService : ILookupDataService<CostLookup> { } 
	public interface ICurrencyLookupDataService : ILookupDataService<CurrencyLookup> { } 
	public interface IExchangeCurrencyRateLookupDataService : ILookupDataService<ExchangeCurrencyRateLookup> { } 
	public interface IProductLookupDataService : ILookupDataService<ProductLookup> { } 
	public interface IOfferLookupDataService : ILookupDataService<OfferLookup> { } 
	public interface IEmployeeLookupDataService : ILookupDataService<EmployeeLookup> { } 
	public interface IOrderLookupDataService : ILookupDataService<OrderLookup> { } 
	public interface IPaymentConditionLookupDataService : ILookupDataService<PaymentConditionLookup> { } 
	public interface IPaymentDocumentLookupDataService : ILookupDataService<PaymentDocumentLookup> { } 
	public interface IFacilityLookupDataService : ILookupDataService<FacilityLookup> { } 
	public interface IProjectLookupDataService : ILookupDataService<ProjectLookup> { } 
	public interface IUserRoleLookupDataService : ILookupDataService<UserRoleLookup> { } 
	public interface ISpecificationLookupDataService : ILookupDataService<SpecificationLookup> { } 
	public interface ITenderLookupDataService : ILookupDataService<TenderLookup> { } 
	public interface ITenderTypeLookupDataService : ILookupDataService<TenderTypeLookup> { } 
	public interface IUserLookupDataService : ILookupDataService<UserLookup> { } 
	public interface IOfferUnitLookupDataService : ILookupDataService<OfferUnitLookup> { } 
	public interface IProductBlockLookupDataService : ILookupDataService<ProductBlockLookup> { } 
	public interface IOfferUnitGroupLookupDataService : ILookupDataService<OfferUnitGroupLookup> { } 
}
