// <auto-generated />
namespace HVTApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddEventServiceUnit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEventServiceUnit));
        
        string IMigrationMetadata.Id
        {
            get { return "202202060816169_AddEventServiceUnit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
