// <auto-generated />
namespace HVTApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class StructureCostNumberIsRequired3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StructureCostNumberIsRequired3));
        
        string IMigrationMetadata.Id
        {
            get { return "202508131018336_StructureCostNumberIsRequired3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
