// <auto-generated />
namespace HVTApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IsUploadedDocumentationToTeamCenter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsUploadedDocumentationToTeamCenter));
        
        string IMigrationMetadata.Id
        {
            get { return "202504111040175_IsUploadedDocumentationToTeamCenter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
