namespace HVTApp.DataAccess
{
    public partial class UnitOfWork
    {
        public void InitializeRepositories()
        {
            CreateNewProductTaskRepository = new CreateNewProductTaskRepository(_context, _container);
            DocumentIncomingNumberRepository = new DocumentIncomingNumberRepository(_context, _container);
            DocumentOutgoingNumberRepository = new DocumentOutgoingNumberRepository(_context, _container);
            PaymentActualRepository = new PaymentActualRepository(_context, _container);
            PaymentPlannedRepository = new PaymentPlannedRepository(_context, _container);
            ProductBlockIsServiceRepository = new ProductBlockIsServiceRepository(_context, _container);
            ProductIncludedRepository = new ProductIncludedRepository(_context, _container);
            ProductDesignationRepository = new ProductDesignationRepository(_context, _container);
            ProductTypeRepository = new ProductTypeRepository(_context, _container);
            ProductTypeDesignationRepository = new ProductTypeDesignationRepository(_context, _container);
            ProjectTypeRepository = new ProjectTypeRepository(_context, _container);
            CommonOptionRepository = new CommonOptionRepository(_context, _container);
            AddressRepository = new AddressRepository(_context, _container);
            CountryRepository = new CountryRepository(_context, _container);
            DistrictRepository = new DistrictRepository(_context, _container);
            LocalityRepository = new LocalityRepository(_context, _container);
            LocalityTypeRepository = new LocalityTypeRepository(_context, _container);
            RegionRepository = new RegionRepository(_context, _container);
            CalculatePriceTaskRepository = new CalculatePriceTaskRepository(_context, _container);
            SumRepository = new SumRepository(_context, _container);
            CurrencyExchangeRateRepository = new CurrencyExchangeRateRepository(_context, _container);
            DescribeProductBlockTaskRepository = new DescribeProductBlockTaskRepository(_context, _container);
            NoteRepository = new NoteRepository(_context, _container);
            OfferUnitRepository = new OfferUnitRepository(_context, _container);
            PaymentConditionSetRepository = new PaymentConditionSetRepository(_context, _container);
            ProductBlockRepository = new ProductBlockRepository(_context, _container);
            ProductDependentRepository = new ProductDependentRepository(_context, _container);
            ProductionTaskRepository = new ProductionTaskRepository(_context, _container);
            SalesBlockRepository = new SalesBlockRepository(_context, _container);
            BankDetailsRepository = new BankDetailsRepository(_context, _container);
            CompanyRepository = new CompanyRepository(_context, _container);
            CompanyFormRepository = new CompanyFormRepository(_context, _container);
            DocumentsRegistrationDetailsRepository = new DocumentsRegistrationDetailsRepository(_context, _container);
            EmployeesPositionRepository = new EmployeesPositionRepository(_context, _container);
            FacilityTypeRepository = new FacilityTypeRepository(_context, _container);
            ActivityFieldRepository = new ActivityFieldRepository(_context, _container);
            ContractRepository = new ContractRepository(_context, _container);
            MeasureRepository = new MeasureRepository(_context, _container);
            ParameterRepository = new ParameterRepository(_context, _container);
            ParameterGroupRepository = new ParameterGroupRepository(_context, _container);
            ProductRelationRepository = new ProductRelationRepository(_context, _container);
            PersonRepository = new PersonRepository(_context, _container);
            ParameterRelationRepository = new ParameterRelationRepository(_context, _container);
            SalesUnitRepository = new SalesUnitRepository(_context, _container);
            TestFriendAddressRepository = new TestFriendAddressRepository(_context, _container);
            TestFriendRepository = new TestFriendRepository(_context, _container);
            TestFriendEmailRepository = new TestFriendEmailRepository(_context, _container);
            TestFriendGroupRepository = new TestFriendGroupRepository(_context, _container);
            DocumentRepository = new DocumentRepository(_context, _container);
            DocumentNumberRepository = new DocumentNumberRepository(_context, _container);
            TestEntityRepository = new TestEntityRepository(_context, _container);
            TestHusbandRepository = new TestHusbandRepository(_context, _container);
            TestWifeRepository = new TestWifeRepository(_context, _container);
            TestChildRepository = new TestChildRepository(_context, _container);
            SumOnDateRepository = new SumOnDateRepository(_context, _container);
            ProductRepository = new ProductRepository(_context, _container);
            OfferRepository = new OfferRepository(_context, _container);
            EmployeeRepository = new EmployeeRepository(_context, _container);
            OrderRepository = new OrderRepository(_context, _container);
            PaymentConditionRepository = new PaymentConditionRepository(_context, _container);
            PaymentDocumentRepository = new PaymentDocumentRepository(_context, _container);
            FacilityRepository = new FacilityRepository(_context, _container);
            ProjectRepository = new ProjectRepository(_context, _container);
            UserRoleRepository = new UserRoleRepository(_context, _container);
            SpecificationRepository = new SpecificationRepository(_context, _container);
            TenderRepository = new TenderRepository(_context, _container);
            TenderTypeRepository = new TenderTypeRepository(_context, _container);
            UserRepository = new UserRepository(_context, _container);
        }


        #region Repositories
        protected ICreateNewProductTaskRepository CreateNewProductTaskRepository;
        protected IDocumentIncomingNumberRepository DocumentIncomingNumberRepository;
        protected IDocumentOutgoingNumberRepository DocumentOutgoingNumberRepository;
        protected IPaymentActualRepository PaymentActualRepository;
        protected IPaymentPlannedRepository PaymentPlannedRepository;
        protected IProductBlockIsServiceRepository ProductBlockIsServiceRepository;
        protected IProductIncludedRepository ProductIncludedRepository;
        protected IProductDesignationRepository ProductDesignationRepository;
        protected IProductTypeRepository ProductTypeRepository;
        protected IProductTypeDesignationRepository ProductTypeDesignationRepository;
        protected IProjectTypeRepository ProjectTypeRepository;
        protected ICommonOptionRepository CommonOptionRepository;
        protected IAddressRepository AddressRepository;
        protected ICountryRepository CountryRepository;
        protected IDistrictRepository DistrictRepository;
        protected ILocalityRepository LocalityRepository;
        protected ILocalityTypeRepository LocalityTypeRepository;
        protected IRegionRepository RegionRepository;
        protected ICalculatePriceTaskRepository CalculatePriceTaskRepository;
        protected ISumRepository SumRepository;
        protected ICurrencyExchangeRateRepository CurrencyExchangeRateRepository;
        protected IDescribeProductBlockTaskRepository DescribeProductBlockTaskRepository;
        protected INoteRepository NoteRepository;
        protected IOfferUnitRepository OfferUnitRepository;
        protected IPaymentConditionSetRepository PaymentConditionSetRepository;
        protected IProductBlockRepository ProductBlockRepository;
        protected IProductDependentRepository ProductDependentRepository;
        protected IProductionTaskRepository ProductionTaskRepository;
        protected ISalesBlockRepository SalesBlockRepository;
        protected IBankDetailsRepository BankDetailsRepository;
        protected ICompanyRepository CompanyRepository;
        protected ICompanyFormRepository CompanyFormRepository;
        protected IDocumentsRegistrationDetailsRepository DocumentsRegistrationDetailsRepository;
        protected IEmployeesPositionRepository EmployeesPositionRepository;
        protected IFacilityTypeRepository FacilityTypeRepository;
        protected IActivityFieldRepository ActivityFieldRepository;
        protected IContractRepository ContractRepository;
        protected IMeasureRepository MeasureRepository;
        protected IParameterRepository ParameterRepository;
        protected IParameterGroupRepository ParameterGroupRepository;
        protected IProductRelationRepository ProductRelationRepository;
        protected IPersonRepository PersonRepository;
        protected IParameterRelationRepository ParameterRelationRepository;
        protected ISalesUnitRepository SalesUnitRepository;
        protected ITestFriendAddressRepository TestFriendAddressRepository;
        protected ITestFriendRepository TestFriendRepository;
        protected ITestFriendEmailRepository TestFriendEmailRepository;
        protected ITestFriendGroupRepository TestFriendGroupRepository;
        protected IDocumentRepository DocumentRepository;
        protected IDocumentNumberRepository DocumentNumberRepository;
        protected ITestEntityRepository TestEntityRepository;
        protected ITestHusbandRepository TestHusbandRepository;
        protected ITestWifeRepository TestWifeRepository;
        protected ITestChildRepository TestChildRepository;
        protected ISumOnDateRepository SumOnDateRepository;
        protected IProductRepository ProductRepository;
        protected IOfferRepository OfferRepository;
        protected IEmployeeRepository EmployeeRepository;
        protected IOrderRepository OrderRepository;
        protected IPaymentConditionRepository PaymentConditionRepository;
        protected IPaymentDocumentRepository PaymentDocumentRepository;
        protected IFacilityRepository FacilityRepository;
        protected IProjectRepository ProjectRepository;
        protected IUserRoleRepository UserRoleRepository;
        protected ISpecificationRepository SpecificationRepository;
        protected ITenderRepository TenderRepository;
        protected ITenderTypeRepository TenderTypeRepository;
        protected IUserRepository UserRepository;
        #endregion
    }
}
